language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install
  - ./vendor/bin/phpcs -n --standard=PSR2 src/ tests/

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
